export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_CONNECTOR = 'ADD_CONNECTOR';
export const ADD_CONNECTOR_SUCCESS = 'ADD_CONNECTOR_SUCCESS';
export const ADD_CONNECTOR_ERROR = 'ADD_CONNECTOR_ERROR';

export const GET_CONNECTORS = 'GET_CONNECTORS';
export const GET_CONNECTORS_SUCCESS = 'GET_CONNECTORS_SUCCESS';
export const GET_CONNECTORS_ERROR = 'GET_CONNECTORS_ERROR';

export const GET_QUERY_DATA = 'GET_QUERY_DATA';
export const GET_QUERY_DATA_SUCCESS = 'GET_QUERY_DATA_SUCCESS';
export const GET_QUERY_DATA_ERROR = 'GET_QUERY_DATA_ERROR';

export const SET_DATE_RANGE = 'SET_DATE_RANGE';

export const APP_NAVIGATE = 'APP_NAVIGATE'